raise Exception("bruh!")
try:
  print("running")
  print(ssssss)
except:
  print("something went wrong!")
  exit(-1)